# ============================================================================
# STAGE 1: Dependencies — install ALL packages (dev deps needed for ng build)
# ============================================================================
FROM oven/bun:1.3.11 AS deps

WORKDIR /app


# Disable Husky hooks for clean CI builds
ENV HUSKY=0 \
    CI=1

# Copy only package manifests — layer is cached until these files change
COPY package.json bun.lockb ./

# Install all deps (dev included: Angular CLI, TypeScript, Tailwind, etc.)
# --ignore-scripts: skip postinstall hooks (Husky, etc.)
RUN bun install --frozen-lockfile --ignore-scripts

# ============================================================================
# STAGE 2: Build — Angular production bundle
# ============================================================================
FROM deps AS build

WORKDIR /app

ENV HUSKY=0 \
    CI=1

# Reuse node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy full source tree — Angular compiler needs tsconfig, src/, backend/, etc.
COPY . .

# Compile Angular app in production mode
# Outputs: dist/treaty/browser/ (static assets) + dist/treaty/server/ (SSR)
RUN bun run build

# Build a standalone executable from source entrypoint for binary-only deployment.
RUN bun run build:runtime:bin:linux

# Prune to production-only node_modules
# Removes: @angular/cli, @angular/build, typescript, vite, wrangler, husky, etc.
RUN bun install --frozen-lockfile --production --ignore-scripts
# Trust all packages so their postinstall/lifecycle scripts are allowed to run
RUN bun pm trust --all
# Re-run install (no --ignore-scripts) so trusted packages execute their lifecycle scripts
# (e.g. SurrealDB downloading its native WASM binary, etc.)
RUN bun install --production

# ============================================================================
# STAGE 3: Runtime — minimal image, no build tools
# ============================================================================
FROM oven/bun:1.3.11 AS runtime

WORKDIR /app

ENV NODE_ENV=production \
    PORT=4201 \
    APP_LOG_LEVEL=info \
    APP_DEBUG_LOGS=false \
    RUN_AS_BIN=true

# Production node_modules only (~60 MB vs ~500 MB with devDeps)
# Contains: @angular/*, elysia, rxjs, surrealdb, @dotenvx/dotenvx, etc.
COPY --chown=bun:bun --from=build /app/node_modules ./node_modules

# Pre-compiled Angular browser + server assets
COPY --chown=bun:bun --from=build /app/dist ./dist

# Encrypted env file is safe to bake into image; key is provided via runtime secret.
COPY --chown=bun:bun --from=build /app/.env.production ./.env.production
COPY --chown=bun:bun --from=build /app/package.json /app/bun.lockb ./

# Switch to non-root user (enables clustering on Linux with uid != 0)
USER bun

EXPOSE 4201

# Health check — waits up to 20 s for startup before marking unhealthy
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD bun -e "fetch('http://127.0.0.1:4201/api/health').then((r)=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"

# Run the AOT-linked production server bundle from Angular output.
CMD ["bun", "--no-env-file", "dist/treaty/server/server.mjs"]

# ============================================================================
# STAGE 4: Runtime Binary — compiled executable only
# ============================================================================
FROM oven/bun:1.3.11 AS runtime-bin

WORKDIR /app

ENV NODE_ENV=production \
    PORT=4201 \
    APP_LOG_LEVEL=info \
    APP_DEBUG_LOGS=false

# Compiled source-entry executable generated by build:runtime:bin.
COPY --chown=bun:bun --from=build /app/dist/runtime/treaty-server ./treaty-server

# Browser and server dist are required so the compiled runtime can reuse
# Angular's production SSR artifacts instead of falling back to source SSR.
COPY --chown=bun:bun --from=build /app/dist/treaty/browser ./dist/treaty/browser
COPY --chown=bun:bun --from=build /app/dist/treaty/server ./dist/treaty/server

# Encrypted env file is safe to bake into image; key is provided via runtime secret.
COPY --chown=bun:bun --from=build /app/.env.production ./.env.production

# Switch to non-root user (enables clustering on Linux with uid != 0)
USER bun

EXPOSE 4201

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD bun -e "fetch('http://127.0.0.1:4201/api/health').then((r)=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"

CMD ["./treaty-server"]
